### ISSUE TITLE
[Feature Request] Dry run mode

### ISSUE THREAD

**Issue by sagittarius-a** [Sinono3/quiren#7]
Dry run could allow user to see changes that will be performed in a list such as:

```
/tmp/asdf/readme.md       -> /tmp/asdf/README.md
/tmp/asdf/Contributing.md -> /tmp/asdf/CONTRIBUTING.md
```

This could be handy to make sure changes are correct. It could be an interactive action where user must confirm renaming.

This could be handled with `-n` and `--dry-run` command line arguments (like the `git clean` command)

**Comment by Sinono3** [comment]
Closed with #8.
